interface TraCredenciales {
  NOMBRE_ESTABLECIMIENTO: string;
  NIT_ESTABLECIMIENTO: string;
  RNT_ESTABLECIMIENTO: string;
  TOKEN_ESTABLECIMIENTO: string;
  ENDPOINT_TRA_PRINCIPAL: string;
  ENDPOINT_TRA_SECUNDARIO: string;
}

const NOMBRE_ESTABLECIMIENTO = 'Hotel San Miguel';
const NIT_ESTABLECIMIENTO = '123456789';
const RNT_ESTABLECIMIENTO = '123456789';
const TOKEN_ESTABLECIMIENTO = '123456789';

const ENDPOINT_TRA_PRINCIPAL = 'https://traapi.mincit.gov.co/api/';
const ENDPOINT_TRA_SECUNDARIO = 'https://traapi.mincit.gov.co/apitwo/';

export const TRA_CREDENCIALES: TraCredenciales = {
  NOMBRE_ESTABLECIMIENTO,
  NIT_ESTABLECIMIENTO,
  RNT_ESTABLECIMIENTO,
  TOKEN_ESTABLECIMIENTO,
  ENDPOINT_TRA_PRINCIPAL,
  ENDPOINT_TRA_SECUNDARIO,
};
